# docker-compose.yml
services:

  nginx:
    image: nginx:latest
    container_name: api-gateway-nginx
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - transaction-service
      - wallet-service
      # - topup-service
    networks:
      - onepay-networks
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && nginx -s reload"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
        context: ./UserService
        dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      ds0:
        condition: service_healthy
      ds1:
        condition: service_healthy
      # ds2:
      #   condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - onepay-networks

  transaction-service:
    build:
        context: ./TransactionService
        dockerfile: Dockerfile
    image: transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
    depends_on:
      postgresql-db-transactions:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - onepay-networks

  wallet-service:
    build:
      context: ./WalletService
      dockerfile: Dockerfile
    container_name: wallet-service
    ports:
      - "8083:8083"
    depends_on:
      postgresql-db-wallet:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - onepay-networks
    environment:
      - DATABASE_URL=postgres://user:password@postgresql-db-wallet:5432/onepay_wallet_db?sslmode=disable
      - KAFKA_BROKERS=broker:9092
      - KAFKA_TOPIC_USER_CREATED=user.created
      - KAFKA_TOPIC_TOPUP_SUCCESS=topup.success
      - KAFKA_TOPIC_WALLET_UPDATED=wallet.updated
      - KAFKA_CONSUMER_GROUP=wallet-service-group
      - APP_PORT=8083
    restart: unless-stopped

  # topup-service:
  #   build:
  #     context: ./TopupService
  #     dockerfile: Dockerfile
  #   # image: topup-service
  #   container_name: topup-service
  #   ports:
  #     - "8084:8084"
  #   depends_on:
  #     postgresql-db-wallet:
  #       condition: service_healthy
  #     broker:
  #       condition: service_healthy
  #   networks:
  #     - onepay-networks
  #   environment:
  #     - DATABASE_URL=postgres://user:password@postgresql-db-wallet:5432/onepay_wallet_db?sslmode=disable
  #     - KAFKA_BROKERS=kafka-broker:9092
  #     - KAFKA_TOPIC_TOPUP_SUCCESS=topup.success
  #     - KAFKA_TOPIC_TOPUP_FAILED=topup.failed
  #     - APP_PORT=8084
  #   restart: unless-stopped

  ds0:
    image: mysql:8.0
    container_name: user_db0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_1
    ports:
      - "3306:3306"
    volumes:
      - user_db0_data:/var/lib/mysql
    networks:
      - onepay-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  ds1:
    image: mysql:8.0
    container_name: user_db1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_2
    ports:
      - "3307:3306"
    volumes:
      - user_db1_data:/var/lib/mysql
    networks:
      - onepay-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
  
  # ds2:
  #   image: postgres:13
  #   container_name: user_db2
  #   restart: always
  #   ports:
  #     - "5436:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: db_3
  #   volumes:
  #     -  user_db2_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10
  #     start_period: 30s
  #   networks:
  #     - onepay-networks

  postgresql-db-transactions:
    image: postgres:13
    container_name: transaction_db0
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions
    volumes:
      - transaction_db0_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - onepay-networks

  postgresql-db-wallet:
    image: postgres:14-alpine
    container_name: wallet_db0
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=onepay_wallet_db
    volumes:
      - wallet_db0_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d onepay_wallet_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - onepay-networks

  broker:
    image: 'bitnami/kafka:latest'
    container_name: kafka-broker
    ports:
      - "9092:9092"
    networks:
      - onepay-networks
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-broker:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data/kraft-combined-logs
      - KAFKA_KRAFT_CLUSTER_ID=WDd1smWIQ-ChsMmr7OLvwQ
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  user_db0_data:
  user_db1_data:
  user_db2_data:
  transaction_db0_data:
  wallet_db0_data:
  kafka_data:
    driver: local

networks:
  onepay-networks:
    driver: bridge