spring.application.name=ReportService
server.port=8085

spring.datasource.url=jdbc:postgresql://postgresql-db-report:5432/report
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=report-service-group

topic.kafka.topup-success=topup.success
topic.kafka.topup-failed=topup.failed
topic.kafka.transaction-success=transaction.success
topic.kafka.transaction-failed=transaction.failed