spring.application.name=ReportService
server.port=8085

spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.url= jdbc:shardingsphere:classpath:sharding.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=report-service-group

topic.kafka.topup-success=topup.success
topic.kafka.topup-failed=topup.failed
topic.kafka.transaction-success=transaction.completed
topic.kafka.transaction-failed=transaction.failed