# ./nginx/nginx.conf
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Definisi upstream untuk layanan Anda
    upstream user_service {
        server user-service:8081;
    }

    upstream transaction_service {
        server transaction-service:8082;
    }

    upstream wallet_service {
        server wallet-service:8083;
    }

    # upstream topup_service {
    #     server topup-service:8084;
    # }

    server {
        listen 80;
        server_name localhost;

        # Routing untuk User Service
        location /api/users {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Routing untuk Transaction Service
        location /api/transactions {
            proxy_pass http://transaction_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/wallets {
            proxy_pass http://wallet_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # location /api/topups {
        #     proxy_pass http://topup_service;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        # }

        # Anda bisa menambahkan location untuk root path atau path lainnya
        location / {
            return 404; # Atau arahkan ke halaman default Anda
        }
    }
}