spring.application.name=NotificationService
server.port=8086

spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.url= jdbc:shardingsphere:classpath:sharding.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=notification-service-group

topic.kafka.topup-success=topup.success
topic.kafka.topup-failed=topup.failed
topic.kafka.transaction-success=transaction.completed
topic.kafka.transaction-failed=transaction.failed

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
