spring.application.name=NotificationService
server.port=8086

spring.datasource.url=jdbc:postgresql://notification_db0:5432/notification_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=notification-service-group

topic.kafka.topup-success=topup.success
topic.kafka.topup-failed=topup.failed
topic.kafka.transaction-success=transaction.completed
topic.kafka.transaction-failed=transaction.failed

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
