server.port=8082
spring.application.name=TransactionService

spring.datasource.url=jdbc:postgresql://postgresql-db-transactions:5432/transactions
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092

# Publisher
app.kafka.transfer-initiated=transfer_initiated
app.kafka.add-receiver-balance=add_receiver_balance
app.kafka.transfer-completed=transfer_completed
app.kafka.transfer-failed=transfer_failed
app.kafka.revert-sender-balance=revert_sender_balance

# Consumer
app.kafka.sender-balance-deducted=sender_balance_deducted
app.kafka.receiver-balance-added=receiver_balance_added
app.kafka.sender-balance-deduction-failed=sender_balance_deduction_failed
app.kafka.receiver-balance-add-failed=receiver_balance_add_failed
app.kafka.sender-balance-reverted=sender_balance_reverted

app.kafka.group.transaction=transaction
