server.port=8082
spring.application.name=TransactionService

spring.datasource.url=jdbc:postgresql://postgresql-db-transactions:5432/transactions
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=transaction-service-group

# Publisher
app.kafka.transfer-initiated=transaction.initiated
app.kafka.transfer-completed=transaction.completed
app.kafka.transfer-failed=transaction.failed

# Consumer
topic.kafka.wallet-transfer-success=wallet.transfer.success
topic.kafka.wallet-transfer-failed=wallet.transfer.failed

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always