spring.application.name=WalletService
server.port=8083

spring.datasource.url=jdbc:postgresql://wallet_db0:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=broker:9092

topic.kafka.user-created=user.created
