spring.application.name=TopupService
server.port=8084

spring.datasource.url=jdbc:postgresql://topup_db0:5432/topup_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.kafka.bootstrap-servers=broker:9092
spring.kafka.consumer.group-id=topup-service-group

# Publisher
topic.kafka.topup-initiated=topup.initiated
topic.kafka.topup-success=topup.success
topic.kafka.topup-failed=topup.failed

# Consumer
topic.kafka.wallet-balance-added=wallet.balance.added
topic.kafka.wallet-balance-deducted=wallet.balance.deducted
topic.kafka.wallet-balance-deduction-failed=wallet.balance.deduction.failed

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always