version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onepay_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wallet-service:
    build: .
    container_name: wallet-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5434/onepay_db?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC_USER_CREATED: onepay.user.created
      KAFKA_TOPIC_TOPUP_SUCCESS: onepay.topup.success
      KAFKA_TOPIC_WALLET_UPDATED: onepay.wallet.updated
      KAFKA_CONSUMER_GROUP: wallet-service-group
      APP_PORT: 8081
    depends_on:
      - postgres
      - kafka

  topup-service:
    build: .
    container_name: topup-service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5434/onepay_db?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      KAFKA_TOPIC_TOPUP_SUCCESS: onepay.topup.success
      KAFKA_TOPIC_TOPUP_FAILED: onepay.topup.failed
      APP_PORT: 8082
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_healthy

volumes:
  postgres_data: